Smtp driver
TykTechnologies/tyk-email-driver pull request #6
Opened 2018-04-05 21:39 UTC by asoorm

example usage
    
```
...
"email_backend": {
  "enable_email_notifications": true,
  "code": "smtp",
  "settings": {
    "SMTPUsername": "ahmet@tyk.io",
    "SMTPPassword": "abcde",
    "SMTPAddress": "smtp.gmail.com:587"
  },
},
...
```

2018-04-05 21:58 UTC, matiasinsaurralde requested changes
Looks good, suggested some tweaks

2018-04-05 21:58 UTC, matiasinsaurralde commented on init.go
> +	if thisInterface, ok = EmailBackendCodes[code]; !ok {
Can we use?
```go
if thisInterface, ok = EmailBackendCodes[code]; !ok {
		return nil, errors.New("no backend with this code was found")
}
return thisInterface, nil
```

2018-04-05 21:58 UTC, matiasinsaurralde commented on smtp.go
> +type SmtpEmailBackend struct {
`SMTPEmailBackend` to make the linter happy?

2018-04-05 22:16 UTC, matiasinsaurralde commented
The official [`SendMail` implementation](https://golang.org/src/net/smtp/smtp.go?s=9230:9308#L309) doesn't support `InsecureSkipVerify`, should we copy/tweak that code in order to allow self-signed certs when using this driver?
cc @martin @buger

2018-04-05 22:25 UTC, asoorm commented
For me, `SendMail` is a nice wrapper - and hides away complexity. In order to make configurable, we need to do as @matiasinsaurralde suggested.

`&tls.Config{ServerName: c.serverName, InsecureSkipVerify: true}` or instead of hardcoding, get it from config.

For me, the MVP is to not support self-signed certs, eventually - if it is a requested/required feature to be configurable, we could do at a later date?

2018-04-05 22:48 UTC, lonelycode commented
> For me, the MVP is to not support self-signed certs and go with current implementation (using stdlib as is). eventually - if it is a requested/required feature to be configurable, we could fork / copy the lib at a later date?

Agree, keep it simple, we can extend later

2018-04-09 14:04 UTC, asoorm commented
This PR does not work where the smtp server requires SSL/TLS, but does not support STARTTLS.

Need to decide whether to implement & maintain a solution which elegantly supports `insecure`, `TLS/SSL` & `STARTTLS` - or whether to use a lib to do for us.

Any preferences @buger @dencoded @matiasinsaurralde ?

2018-04-09 14:10 UTC, buger commented
Well, we for sure not should maintain our own lib, since Go smtp package already has TLS support https://golang.org/pkg/net/smtp/

Example usage: https://gist.github.com/jim3ma/b5c9edeac77ac92157f8f8affa290f45

So if TLS enabled in config, you just need to call StartTLS before Auth

2018-04-09 14:18 UTC, dencoded commented
@asoorm  I think the simplest approach with using standard `smtp.SendMail` would be enough as this method does `StartTLS` and upgrades connection to TLS if server supports `STARTTLS` extension.

According to self-signed certs for smtp-server/insecure - I am not sure that it is a typical case.

2018-04-09 14:29 UTC, asoorm commented
@dencoded In the case that the SMTP server requires TLS, but does not support `STARTTLS`, then will fail. It will not be able to upgrade the insecure connection.

2018-04-09 14:43 UTC, buger commented
How common is not to support STARTLS and support TLS?

2018-04-09 15:05 UTC, asoorm commented
@buger According to: https://www.fastmail.com/help/technical/ssltlsstarttls.html

> Currently, things seem relatively randomly split between people using SMTP SSL/TLS encrypted over port 465, and people using SMTP with STARTTLS upgrading over port 587.

So I know this is just one src, and I honestly don't know how reliable, but it looks like it could be 50/50 split - meaning we should support both.

2018-04-09 15:11 UTC, buger commented
Lets start with STARTTLS only support, and will work based on user feedback. @Pinpin31 does it sounds good?

2018-04-09 15:34 UTC, Pinpin31 commented
Unfortunately, my smtp server don't support STARTTLS but require TLS. I try the pull request and the code fail.

There is  a comment on this github with a code that support STARTTLS or/and TLS : https://github.com/golang/go/issues/13694

I think the code works for all case. It works with my smtp server with parameters  :

  useTls     := true
  useStartTls:= false

```go
package main

import (
	"net/smtp"
	"fmt"
	"strconv"
	"net"
	"crypto/tls"
	"encoding/base64"
)

func main() {
  smtpHost   := "mail.{domain}.com"
  smtpPort   := 587
  smtpLogin  := "{user}@{domain}.com"
  smtpPasswd := "{password}"

  useTls     := true
  useStartTls:= false

  from := "{from@...}"
  to   := "{to@...}"
	title := "Just the sample message"

	body := "Sample message that is";

	header := make(map[string]string)
	header["From"] = from
	header["To"] = to
	header["Subject"] = title
	header["MIME-Version"] = "1.0"
	header["Content-Type"] = "text/plain; charset=\"utf-8\""
	header["Content-Transfer-Encoding"] = "base64"

	message := ""
	for k, v := range header {
		message += fmt.Sprintf("%s: %s\r\n", k, v)
	}
	message += "\r\n" + base64.StdEncoding.EncodeToString([]byte(body))

	conn, err := net.Dial("tcp", smtpHost+":"+strconv.Itoa(smtpPort))
	if err != nil {
		fmt.Println(err)
		return
	}

	// TLS
	tlsconfig := &tls.Config{
		InsecureSkipVerify: true,
		ServerName: smtpHost,
	}

	if useTls {
		conn = tls.Client(conn, tlsconfig)
	}

	client, err := smtp.NewClient(conn, smtpHost)
	if err != nil {
		fmt.Println(err)
		return
	}

	hasStartTLS, _ := client.Extension("STARTTLS")
	if useStartTls && hasStartTLS {
		fmt.Println("STARTTLS ...")
		if err = client.StartTLS(tlsconfig); err != nil {
			fmt.Println(err)
			return
		}
	}

	// Set up authentication information.
	auth := smtp.PlainAuth(
		"",
		smtpLogin,
		smtpPasswd,
		smtpHost,
	)

	if ok, _ := client.Extension("AUTH"); ok {
		if err := client.Auth(auth); err != nil {
			fmt.Printf("Error during AUTH %s\n", err)
			return
		}
	}
	fmt.Println("AUTH done")

	if err := client.Mail(from); err != nil {
		fmt.Printf("Error: %s\n", err)
		return
	}
	fmt.Println("FROM done")

	if err := client.Rcpt(to); err != nil {
		fmt.Printf("Error: %s\n", err)
		return
	}
	fmt.Println("TO done")

	w, err := client.Data()
	if err != nil {
		fmt.Printf("Error: %s\n", err)
		return
	}

	_, err = w.Write([]byte(message))
	if err != nil {
		fmt.Printf("Error: %s\n", err)
		return
	}

	err = w.Close()
	if err != nil {
		fmt.Printf("Error: %s\n", err)
		return
	}

	client.Quit()
}
```

2018-04-09 15:36 UTC, buger commented
In general doing TLS connection if param is passed should not be an issue too, you just do not need to use SendEmail function, or probably just copy-paste its original implementation and add additionall attribute which should explicitly enable TSL https://golang.org/src/net/smtp/smtp.go?s=9230:9308#L319

2018-04-10 06:26 UTC, Pinpin31 commented
Maybe you could use this library : https://github.com/go-gomail/gomail
It seems possible to switch easily in TLS or not :

```go
package main

import (
    "gopkg.in/gomail.v2"
    "crypto/tls"
)

func main() {
    m := gomail.NewMessage()
    m.SetHeader("From", "nilton@domain.com")
    m.SetHeader("To", "nilton@domain2.com")
    m.SetHeader("Subject", "Hello!")
    m.SetBody("text/html", "Hello <b>Nilton OS</b>!")

    // Send the email to Bob
    d := gomail.NewPlainDialer("mail.domain.com", 587, "nilton@domain.com", "1234567")
    d.TLSConfig = &tls.Config{InsecureSkipVerify: true}
    if err := d.DialAndSend(m); err != nil {
        panic(err)
    }
}
```

2018-04-10 07:49 UTC, Pinpin31 commented
I do a commit with gomail in my first pull request if you want to test :
https://github.com/TykTechnologies/tyk-email-driver/pull/5

2018-04-10 09:07 UTC, asoorm commented
I agree with going down the library route to avoid re-inventing the wheel, and adding unnecessary maintenance overhead. I will research `gomail` and some other libs today/tomorrow.

2018-04-12 09:29 UTC, dencoded commented on init.go
> +		return nil, errors.New("no backend with this code was found")
using predefined vars with errors could simplify unit-tests asserts

2018-04-12 09:36 UTC, dencoded commented on smtp.go
> +func (m *SMTPEmailBackend) Send(emailMeta EmailMeta, emailData interface{}, textTemplateName TykTemplateName,
we could cover this function by tests

2018-04-12 09:36 UTC, dencoded commented on smtp.go
> +func (m *SMTPEmailBackend) Init(conf map[string]string) error {
we could cover this function by tests

2018-04-12 09:39 UTC, dencoded commented on smtp.go
> +		log.Error("error executing text template:", err)
would be better to follow logging API `log.WithError(err).Error("error executing text template")`

2018-04-12 09:42 UTC, dencoded commented on smtp.go
> +		log.Error("error sending mail:", err)
one more spot for `log.WithError(err).`

2018-04-12 09:44 UTC, dencoded commented on smtp.go
> +	log.Debugf("email sent addr: %s, from: %s, to: %s", m.host, emailMeta.FromEmail, emailMeta.RecipientEmail)
might be better to use `log.WithFields(...).Debug("email sent")` as logging library is supposed to simplify format output code like this

2018-04-12 09:52 UTC, dencoded requested changes
just add some simple unit test for initialization + some minor comments about logging

2018-04-12 11:01 UTC, asoorm commented on smtp.go
> +func (m *SMTPEmailBackend) Init(conf map[string]string) error {
done. see `smtp_test.go`

2018-04-12 12:11 UTC, dencoded approved these changes

2018-04-12 14:08 UTC, matiasinsaurralde approved these changes
Looks good!

2018-04-12 15:09 UTC, Pinpin31 commented
I test this version with my smtp server and it works fine.
It's great !
Tanks

2018-04-13 08:40 UTC, merged